

GET http://localhost:7070/lectures/1/tasks

### 

GET http://localhost:7070/tasks/1

### 

POST http://localhost:7070/lectures/1/tasks
Content-Type: application/json

{
    "task": {
        "name": "Summ of two numbers",
        "description": "Create function that calculate summ of a and b and export them",
        "content": "Create function that calculate summ of a and b and export them"
    },
    "cases": [
        {
            "name": "10 + 5",
            "input": "{ a: 10, b: 5 }",
            "expect": "15"
        }
    ]
}